### PR TITLE
Feature random initiative

### PR DESCRIPTION
**Pull request by vforvasile**
Hi!

Thanks for the tool you created, I was using dm.tools and struggled with player/creature conditions & lack of other features that I found in your project.

I added 2 tiny improvements:
- D20 button near the initiative input, to randomize a value (tried to follow your UI)
- Randomized initiative for creatures when initiative is **present** and multiplier is applied (e.g. For 3 Goblins, when initiative is typed/rolled **11**, other 2 goblins will have generated initiative.) 

Screenshot 2023-01-02 at 12 02 28

Those 2 improvements are useful for me, it's completely alright if you don't want to implement them. 

Happy Holidays!

### CODE REVIEW

**Comment by Paul-Ladyman** [comment]
Hi @vforvasile !

First of all, thank you very much for taking the time to put together these PRs (I've seen https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/505 as well). I've only had one other PR in the last few years so I really appreciate it.

**D20 Button**

This is cool and preempts a dice rolling feature I was intending on working on (https://github.com/Paul-Ladyman/dnd-battle-tracker/issues/436). I think this would be a nice solution in the interim to help you and I'm sure others out in your sessions.

**Random initiative for multiplied creatures**

This is also cool.

I'd like to keep the ability to have a single initiative score for all the creatures in the group. This is how the PHB suggests things should be done, "The DM makes one roll for an entire group of identical creatures, so each member of the group acts at the same time" (p189).

I've already thought a little how I'd combine this with a random initiative roll and I'm still not sure. Perhaps if the user clicks the D20 button, we roll a separate initiative for each creature in the group, where as if a value is typed in we use that same value for each creature. What do you think?

**Merging**

There's some tests failing in the status checks and there may be some other problems to look at too.

It's totally up to you how much time you want to put into these PRs, I know tests aren't everyone's thing particularly for a hobby project! If you want you could treat them more as feature suggestions and I'll work on them when I find some time.

I'll also do some reviewing and testing when I find the time so it may take me a little while but I'm well up for PRs from other DMs so I will get to it and thanks again!

**Comment by vforvasile** [comment]
> I've already thought a little how I'd combine this with a random initiative roll and I'm still not sure. Perhaps if the user clicks the D20 button, we roll a separate initiative for each creature in the group, where as if a value is typed in we use that same value for each creature. What do you think?

Maybe add a toggle, when multiplier value is bigger than 1, sync inititiative/same initiative dunno.

> D20 Button

This is cool and preempts a dice rolling feature I was intending on working on (https://github.com/Paul-Ladyman/dnd-battle-tracker/issues/436). I think this would be a nice solution in the interim to help you and I'm sure others out in your sessions.

About the D20 button, I was thinking to combine DEX modifier for the creatures (from the other PR) and add it to the roll on click, however there's no TS is in the project and it's easy to mess things up

**Comment by Paul-Ladyman** [comment]
There's a lot of cool stuff in that video! Very exciting!

One thought, how are things looking on mobile screen sizes? There's a lot of new information to cram in there.

I'd like to work towards getting these new features merged and deployed. Ideally it would be good if we could break them up into small chunks so I can review and test them more easily. Basically the smaller the PR you can give me the better!

Is this PR and https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/505 still valid after the new work you did, should I start with those?

**Comment by vforvasile** [comment]
Here's a peak on mobile:

https://user-images.githubusercontent.com/9382283/211139508-b86a42ca-5c4e-4a6e-b28e-92852b2936fb.mp4

I have to think on how to split them and how to fix some tests (this is on my master branch after merging all the features)

Screenshot 2023-01-07 at 09 35 07

**Comment by Paul-Ladyman** [comment]
Oh yeah mobile actually looks fine from that video! Anyway as long as it's not completely broken I don't mind merging and then following up with improvements.

Also I spotted the creature name links you mentioned you'd added in https://github.com/Paul-Ladyman/dnd-battle-tracker/issues/435#issuecomment-1373831960, brilliant!

Take your time figuring out how best to split everything up. I can help out dealing with the tests once the branches are ready. I've been trying to increase my test coverage lately, especially for the UI, so if you felt like adding some for the new features that's great (with a preference for [integration tests](https://github.com/Paul-Ladyman/dnd-battle-tracker/tree/master/test-integration)). But if manual testing looks good I'll probably merge anyway and then add some automated tests on the main branch.

Thanks again for all this work, so many great new features! Looking forward to releasing them for everyone to enjoy.

**Comment by Paul-Ladyman** [comment]
I fixed the tests on this branch. The tests for adding multiple creatures were failing because they expected both new creatures to use the same initiative, whereas the second one now uses a random initiative. I mocked out `rollDice` to give a consistent value for the random number. A similar approach could be used for the "random init" toggle.

Would it be useful for me to merge this branch or do you want to go from your other branch(es) where you've developed things further?

**Comment by Paul-Ladyman** [comment]
I'm going to merge and deploy this branch so people can start using your awesome new feature! I've removed the random initiative for multiplied creatures for now as we'll be adding the toggle button to activate this functionality later.

Thanks again for this!

**Comment by vforvasile** [comment]
Sorry, I've been very busy last week, I'll see what I can do about the next PRs in the following days

**Comment by Paul-Ladyman** [comment]
No problem at all Vasile just take your time and we'll deploy things when they're ready.

**Pull request merged**
