### PR TITLE
Add scroll to active initiative 

### PR DESCRIPTION
**Pull request by vforvasile**
## Scroll to active initiative from header

I forked it again from an organization cause my fork is too far ahead and behind as well 😆 .

### Improvements:

1) This part could be improved with responsive approach, I haven't tested many scenarios with different device dimensions

```
.creature-scroll-effect {
  scroll-margin-top: 120px;
}
```

2) Maybe add for Player Session component? (dunno how relevant is this)

### Preview

https://user-images.githubusercontent.com/9382283/212894552-99b4514a-79d4-4ad2-b5f9-b89718986cd7.mp4

### CODE REVIEW

**Comment by Paul-Ladyman** [comment]
Haha yeah we're changing a lot. But that's good! :smile: .

I'll do some responsive testing. I also have a [staging environment](https://dndbattletracker.com/stage/) we could use to try things out on real devices.

This is totally relevant to the Player component as well, in fact it would be great to add it there too.

The test failures are just a couple of accessibility errors as there's a div that's clickable but has no keyboard interactions. Best thing would probably be to just make that div a button and sort out the styling a little bit.

The scrolling animation looks great! I should maybe copy that for the next turn button as it positions the creature more nicely on the page.

I think this one should be fairly quick to sort out and deploy so I'll hopefully I'll be able to do that soon.

**Comment by Paul-Ladyman** [comment]
Great PR by the way. Keeping them smaller and specific to one new feature like this really helps me out and means I can keep things deployed quicker.

**Comment by vforvasile** [comment]
> This is totally relevant to the Player component as well, in fact it would be great to add it there too.

I just added a commit to feature this for Player as well

> The scrolling animation looks great! I should maybe copy that for the next turn button as it positions the creature more nicely on the page.

Take a look at this preview, I'm not sure if this is the result you were thinking about:

https://user-images.githubusercontent.com/9382283/213410915-7ea240a5-37f5-4793-83f1-131a2eaf3575.mp4

Added an **autoscroll** for players when initiative changes (uses the same function)

> The test failures are just a couple of accessibility errors as there's a div that's clickable but has no keyboard interactions. Best thing would probably be to just make that div a button and sort out the styling a little bit.

Yeah, I noticed eslint failed. I attempted to add a button but broke the whole styling for the header and didn't want to mess everything 😄

**Comment by Paul-Ladyman** [comment]
> Take a look at this preview, I'm not sure if this is the result you were thinking about
Yes that's what I meant! Might look good for the DM too to autoscroll when the initiative changes. I think your animation makes it more obvious what's happened.

**Comment by Paul-Ladyman** [comment]
Hi @vforvasile. I have a local commit for your fork branch that uses a button with a style that looks OK (not great!) I can't push my changes though, I think you need to give me permission to do so like with the previous PRs.

**Comment by vforvasile** [comment]
Hi @Paul-Ladyman!

I think the issue might come from organisation fork, I added you as a writer here, sorry for the inconvenience.

**Comment by vforvasile** [comment]
> Yes that's what I meant! Might look good for the DM too to autoscroll when the initiative changes. I think your animation makes it more obvious what's happened.

Just added this in the last commit

**Comment by Paul-Ladyman** [comment]
I got the button merged in and added some integration tests so the checks should be looking pretty good now.

I remember now that when I was building the share feature I decided not to have the PlayerApp automatically scroll to the current initiative as it would likely be annoying if a player was looking at something else and suddenly the page jumped out of their control. Probably an accessibility problem too. I've disabled this for now but maybe we could think about an option to toggle this feature on and off in a future PR.

I've disabled the autoscroll for the DM App too but only temporarily as I think the old, less cool, version was still active and so the page was jumping around as the two animations happened at the same time. I'll disable the old version and see if that makes it better.

**Comment by vforvasile** [comment]
Looks good. 

Yeah, the autoscroll for players could disturb the view sometimes. I even found an issue when clicking **share session**, previous initiative from reference is undefined or null and it scrolls to active initiative.

In case you want to use this in the future, a quick fix would be:

``` 
useEffect(() => {
    if (typeof prevActiveCreature.current === 'number' && prevActiveCreature.current !== activeCreatureId) {
      onScrollActiveInitiative(activeCreatureId);
    }
    prevActiveCreature.current = activeCreatureId;
  }, [activeCreatureId, onScrollActiveInitiative]);
```

**Comment by Paul-Ladyman** [comment]
Unfortunately fixing the DM autoscroll animation involves removing the focus that's applied to the [Creature Expander button](https://github.com/Paul-Ladyman/dnd-battle-tracker/blob/master/src/components/buttons/CreatureExpander.js#L20) and this in turn breaks the hotkeys for moving focus up and down the initiative order (ctrl+shift+up/down-arrow). We could probably get everything to work correctly but the code for managing focus is fairly complex so it will be tricky.

I'm planning an overhaul of the Creature Toolbar interface which should let me greatly simplify focus management. Once this is done it should be much easier to add autoscrolling without messing things up.

So yeah it's a shame to autoscrolling as it looked cool but it will let us get the current turn button deployed and move on. I'll create issues for autoscrolling in the DM and Player Apps so I don't forget as I think they're both nice touches.

Otherwise I think I'm about ready to deploy this!

**Pull request merged**
