### PR TITLE
Add creature Info with highlights

### PR DESCRIPTION
**Pull request by vforvasile**
## Creature info

This PR was built on top of [#505](https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/505) and some discussions were held here: [#504](https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/504)

###  What's New:
- Fetch Creature Data with  [dnd5eapi](https://www.dnd5eapi.co/docs/#get-/api/monsters) (found in **creature.apiData**)
- Creature stats dropdown with creature card (tried to copycat the D&D Beyond card)
- Creature stats highlights for Hit & Damage
- Creature stats damage types emojis
- Toggle to keep same or generate random initiative for creature/multiplier
- Calculate initiative for creatures based on DEX modifier

### Notes
- added react-highlight-words & react-switch because I needed a quick solution 😄 
- removed AC implementation since it will break more stuff
- the styling of the card could use some rework (the one used was inspired by a jsfiddle)
- the creature search dropdown could be improved a lot (I used a class already created by you)
- not synced with base repository master yet

### What breaks
- a lot of tests, since with have apiData in creature object now
- player session also breaks

### Web view:

https://user-images.githubusercontent.com/9382283/210966020-dfb2a96c-ded2-4c99-9340-b5cd58badbd1.mp4

### Mobile view:

https://user-images.githubusercontent.com/9382283/211139508-b86a42ca-5c4e-4a6e-b28e-92852b2936fb.mp4

_p.s. Scroll to active initiative from the mobile preview needs a separate PR_ 

_p.p.s. Improvements are highly encouraged, although I didn't work with the web stack for a long while._

### CODE REVIEW

**Comment by vforvasile** [comment]
maybe pushing package.lock was a bad idea cause I'm on M1 chipset

**Comment by Paul-Ladyman** [comment]
Lovely! I'll start taking a look through this when I can and see about working through some of the fixes and improvements you mention. I _might_ merge https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/505 first (I know you closed it) to just focus on the create creature form bit but we'll see.

For the creature search dropdown I was thinking of using the same kind of interface as the tool for adding/editing notes. I might do some work on main to make that easier to reuse ahead of this.

**Comment by Paul-Ladyman** [comment]
For the package-lock it's good to have merged it as you've added some new dependencies. NPM should take care of the differences in OS/hardware. I'll have to have a look at resolving the conflicts though...if this is a older branch of yours they might be due to some dependabot updates I merged a week or so ago.

**Comment by Paul-Ladyman** [comment]
I've updated the interface for rolling initiative. It's now possible to provide an initiative as dice notation, e.g. 1d20+2. This will be automatically filled in if you select a creature from dnd5eapi. This is a feature I've wanted to add for a while and it means that the modifier to use for rolling initiative is now accessible to the user. The roll initiative button is replaced by a button to toggle between rolling for each creature separately or the whole group. So the initiative functionality that was included in this PR hasn't changed, just the interface. This also means we don't have to worry about squeezing an extra field into the create creature form. All of this is now available on the live website.

What's left in this PR is just the work to add the creature stat blocks retrieved from dnd5eapi, which is the last thing to review and merge from all your great contributions.

Thanks again @vforvasile!

**Comment by Paul-Ladyman** [comment]
The more I work on the stat block the more I wonder if it's the best direction to take.

It would definitely be convenient to have the stat blocks to hand but they're quite complicated! And D&D Beyond has already done a great job of creating them. The [archmage](https://www.dndbeyond.com/monsters/archmage) page for example is so rich and full of additional information like spell descriptions. And there's other tools like [Beyond20](https://chrome.google.com/webstore/detail/beyond-20/gnblbpbepfbfmoobegdogkglpbhcjofh?hl=en) that add even more features. I'm worried that it would be quite a lot of work to create and maintain stat blocks that look good and work right across every monster in the SRD and it would never be as good as D&D Beyond anyway!

Maybe what I should do is improve the integration of D&D Beyond. Right now you can search for any monster using the magnifying glass icon but I could map each monster from dnd5eapi to a specific D&D Beyond URL and provide a direct link. If having an embedded stat block was really important it could maybe be done with an iframe but I don't know how great that would end up looking.

Any thoughts welcome!

**Comment by vforvasile** [comment]
@Paul-Ladyman , feel free to close the PR. I added this mostly for my own usage and thought that someone else might find it useful.

Regarding creature spells formatting, I missed that detail, thanks, I'll try implement it later

**Comment by Paul-Ladyman** [comment]
I've just deployed v5.26.1 which adds direct links to D&D Beyond stat blocks for monsters added from dnd5eapi. I'm thinking this works if a user just needs access to the original stat block. But I have some ideas off the back of this work to use the API data to augment the info in the battle tracker to help out DMs. For example I can prevent a condition being added to a creature if it is immune.

I'll close this PR now. Thanks again for all your contributions @vforvasile. The site has taken a leap forward in functionality and there's a bunch more ideas that it's generated that I can start working on.

**Pull request closed without merging**
